<?php

use Illuminate\Database\Seeder;

class PemeriksaanFisikWebTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contents = json_decode(file_get_contents(storage_path('database/pemeriksaanFisik.json')));
        foreach($contents as $content) {
            DB::table('pemeriksaan_fisik')->insert([
                "id"=> $content->id_pemeriksaan_fisik,
                "id_pasien"=> $content->id_pasien,
                "kunjungan"=> intval($content->kunjungan),
                "tglPeriksa"=> $content->tgl_periksa,
                "td" => intval($content->td),
                "td2" => intval($content->td2),
                "nadi" => intval($content->nadi),
                "tb" => intval($content->tb),
                "bb" => intval($content->bb),
                "kesadaran" => $content->kesadaran,
                "ks1"=> intval($content->ks1),
                "ks2"=> intval($content->ks2),
                "ks3"=> intval($content->ks3),
                "ks4"=> intval($content->ks4),
                "ks5"=> intval($content->ks5),
                "ks6"=> intval($content->ks6),
                "ks7"=> intval($content->ks7),
                "ks8"=> intval($content->ks8),
                "ks9"=> intval($content->ks9),
                "ks10"=> intval($content->ks10),
                "ks11"=> intval($content->ks11),
                "ks12"=> intval($content->ks12),
                "ks13"=> intval($content->ks13),
                "ks14"=> intval($content->ks14),
                "ks15"=> intval($content->ks15),
                "ks16"=> intval($content->ks16),
                "ks17"=> intval($content->ks17),
                "ks18"=> intval($content->ks18),
                "ks19"=> intval($content->ks19),
                "ks20"=> intval($content->ks20),
                "ks21"=> intval($content->ks21),
                "ks22"=> intval($content->ks22),
                "ks23"=> intval($content->ks23),
                "ks24"=> intval($content->ks24),
                "ks25"=> intval($content->ks25),
                "ks26"=> intval($content->ks26),
                "ks27"=> intval($content->ks27),
                "ks28"=> intval($content->ks28),
                "ks29"=> intval($content->ks29),
                "ks30"=> intval($content->ks30),
                "ks31"=> intval($content->ks31),
                "ks32"=> intval($content->ks32),
                "ks33"=> intval($content->ks33),
                "ks34"=> intval($content->ks34),
                "ks35"=> intval($content->ks35),
                "ks36"=> intval($content->ks36),
                "ks37"=> intval($content->ks37),
                "ks38"=> intval($content->ks38),
                "ks39"=> intval($content->ks39),
                "ks40"=> intval($content->ks40),
                "ks41"=> intval($content->ks41),
                "ks42"=> intval($content->ks42),
                "ks43"=> intval($content->ks43),
                "ks44"=> intval($content->ks44),
                "ks45"=> intval($content->ks45),
                "ks46"=> intval($content->ks46),
                "ks47"=> intval($content->ks47),
                "ks48"=> intval($content->ks48),
                "ks49"=> intval($content->ks49),
                "ks50"=> intval($content->ks50),
                "ks51"=> intval($content->ks51),
                "ks52"=> intval($content->ks52),
                "ks53"=> intval($content->ks53),
                "ks54"=> intval($content->ks54),
                "ks55"=> intval($content->ks55),
                "ks56"=> intval($content->ks56),
                "ks57"=> intval($content->ks57),
                "ks58"=> intval($content->ks58),
                "ks59"=> intval($content->ks59),
                "ks60"=> intval($content->ks60),
                "ks61"=> intval($content->ks61),
                "ks62"=> intval($content->ks62),
                "ks63"=> intval($content->ks63),
                "ks64"=> intval($content->ks64),
                "ks65"=> intval($content->ks65),
                "ks66"=> intval($content->ks66),
                "ks67"=> intval($content->ks67),
                "ks68"=> intval($content->ks68),
                "ks69a"=> intval($content->ks69a),
                "ks69b"=> intval($content->ks69b),
                "ks69c"=> intval($content->ks69c),
                "ks69d"=> intval($content->ks69d),
                "ks69e"=> intval($content->ks69e),
                "ks69f"=> intval($content->ks69f),
                "ks69g"=> intval($content->ks69g),
                "ks69h"=> intval($content->ks69h),
                "ks69i"=> intval($content->ks69i),
                "ks69j"=> intval($content->ks69j),
                "ks69k"=> intval($content->ks69k),
                "ks69l"=> intval($content->ks69l),
                "ks70"=> intval($content->ks70),
                "sl1"=> intval($content->sl1),
                "sl1a"=> intval($content->sl1a),
                "sl2"=> intval($content->sl2),
                "sl2a"=> intval($content->sl2a),
                "sl3"=> intval($content->sl3),
                "sl3a"=> intval($content->sl3a),
                "sl4"=> intval($content->sl4),
                "sl4a"=> intval($content->sl4a),
                "sl5"=> intval($content->sl5),
                "sl5a"=> intval($content->sl5a),
                "sl6"=> intval($content->sl6),
                "sl6a"=> intval($content->sl6a),
                "sl7"=> intval($content->sl7),
                "sl7a"=> intval($content->sl7a),
                "sl8"=> intval($content->sl8),
                "sl8a"=> intval($content->sl8a),
                "sl9"=> intval($content->sl9),
                "sl9a"=> intval($content->sl9a),
                "sl10"=> intval($content->sl10),
                "sl10a"=> intval($content->sl10a),
                "sl11"=> intval($content->sl11),
                "sl12"=> intval($content->sl12),
                "sl13"=> intval($content->sl13),
                "sl14"=> intval($content->sl14),
                "sl15"=> intval($content->sl15),
                "sl16"=> intval($content->sl16),
                "sl17"=> intval($content->sl17),
                "sl18"=> intval($content->sl18),
                "sl19"=> intval($content->sl19),
                "sl20"=> intval($content->sl20),
                "sl21"=> intval($content->sl21),
                "sl22"=> intval($content->sl22),
                "sl23"=> intval($content->sl23),
                "sl24"=> intval($content->sl24),
                "sl24a"=> intval($content->sl24a),
                "sl25"=> intval($content->sl25),
                "sl26"=> intval($content->sl26),
                "sl27"=> intval($content->sl27),
                "created_by" => $content->user_id,
                "last_updated_by" => $content->user_id,
            ]);
        }
    }
}
