<?php

use Illuminate\Database\Seeder;

class PemeriksaanPenunjangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contents = json_decode(file_get_contents(storage_path('database/pemeriksaanPenunjang.json')));
        foreach($contents as $content) {
            DB::table('pemeriksaan_penunjang')->insert([
                "id"=> $content->id_pemeriksaan_penunjang,
                "id_pasien"=> $content->id_pasien,
                "kunjungan"=> intval($content->kunjungan),
                "tglPeriksa"=> $content->tgl_periksa,
                "a1"=> 	$content->a1,  
                "a2"=> 	$content->a2,
                "a3"=> 	$content->a3,
                "a4"=> 	$content->a4,
                "a4a"=>	$content->a4a,
                "a5"=> 	$content->a5,
                "a6"=> 	$content->a6,
                "a7"=> 	$content->a7,
                "a7a"=>	$content->a7a,
                "a8"=> 	$content->a8,
                "a9"=> 	$content->a9,
                "a10"=>	$content->a10,
                "a11"=>	$content->a11,
                "a12"=>	$content->a12,
                "a13"=>	$content->a13,
                "a14"=>	$content->a14,
                "a15"=>	$content->a15,
                "a16"=>	$content->a16,
                "a16a"=>$content->a16a,
                "a17"=> $content->a17,
                "a18"=> $content->a18,
                "a19"=> $content->a19,
                "a20"=> $content->a20,
                "a201"=>$content->a201,
                "a202"=>$content->a202,
                "a203"=>$content->a203,
                "a20a"=>$content->a20a,
                "a21"=> $content->a21,
                "a22"=> $content->a22,
                "a23"=> $content->a23,
                "a24"=> $content->a24,
                "a241"=>$content->a241,
                "a242"=>$content->a242,
                "a243"=>$content->a243,
                "a24a"=>$content->a24a,
                "a25"=> $content->a25,
                "a26"=> $content->a26,
                "a27"=> $content->a27,
                "a28"=> $content->a28,
                "a281"=>$content->a281,
                "a282"=>$content->a282,
                "a283"=>$content->a283,
                "a28a"=>$content->a28a,
                "a29"=> $content->a29,
                "a30"=> $content->a30,
                "a31"=> $content->a31,
                "a32"=> $content->a32,
                "a321"=>$content->a321,
                "a322"=>$content->a322,
                "a323"=>$content->a323,
                "a32a"=>$content->a32a,
                "a33"=> $content->a33,
                "a34"=> $content->a34,
                "a35"=> $content->a35,
                "a36"=> $content->a36,
                "a361"=>$content->a361,
                "a362"=>$content->a362,
                "a363"=>$content->a363,
                "a36a"=>$content->a36a,
                "a37"=> $content->a37,
                "a38"=> $content->a38,
                "a39"=> $content->a39,
                "a40"=> $content->a40,
                "a401"=>$content->a401,
                "a402"=>$content->a402,
                "a403"=>$content->a403,
                "a40a"=>$content->a40a,
                "a41"=> $content->a41,
                "a42"=> $content->a42,
                "a43"=> $content->a43,
                "a44"=> $content->a44,
                "a441"=>$content->a441,
                "a442"=>$content->a442,
                "a443"=>$content->a443,
                "a44a"=>$content->a44a,
                "a45"=> $content->a45,
                "a45a"=>$content->a45a,
                "a46"=> $content->a46,
                "a47"=> $content->a47,
                "a48"=> $content->a48,
                "a49"=> $content->a49,
                "a50"=> $content->a50,
                "a51"=> $content->a51,
                "a52"=> $content->a52,
                "a53"=> $content->a53,
                "a54"=> $content->a54,
                "a55"=> $content->a55,
                "a56"=> $content->a56,
                "a57"=> $content->a57,
                "a58"=> $content->a58,
                "a59"=> $content->a59,
                "a60"=> $content->a60,
                "a601"=>$content->a601,
                "a602"=>$content->a602,
                "a603"=>$content->a603,
                "a61"=> $content->a61,
                "a62"=> $content->a62,
                "a63"=> $content->a63,
                "a64"=> $content->a64,
                "a65"=> $content->a65,
                "a66"=> $content->a66,
                "a67"=> $content->a67,
                "sl1"=> $content->sl1,
                "sl2"=> $content->sl2,
                "sl3"=> $content->sl3,
                "sl4"=> $content->sl4,
                "sl5"=> $content->sl5,
                "sl6"=> $content->sl6,
                "sl7"=> $content->sl7,
                "sl8"=> $content->sl8,
                "sl9"=> $content->sl9,
                "sl10"=>$content->sl10,
                "created_by" => $content->user_id,
                "last_updated_by" => $content->user_id,
            ]);
        }
    }
}
