<?php

use Illuminate\Database\Seeder;

class PemeriksaanFisikWebTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contents = json_decode(file_get_contents(storage_path('database/anamnesis.json')));
        foreach($contents as $content) {
            DB::table('pemeriksaan_fisik')->insert([
                "id"=> $content->id_pemeriksaan_fisik,
                "id_pasien"=> $content->id_pasien,
                "Kunjungan"=> $content->kunjungan,
                "tglPeriksa"=> $content->tgl_periksa,
                "td" => $content->td,
                "td2" => $content->td2,
                "nadi" => $content->nadi,
                "tb" => $content->tb,
                "bb" => $content->bb,
                "medrec"=> $content->medrec,
                "kesadaran" => $content->kesadaran,
                "ks1"=> $content->ks1,
                "ks2"=> $content->ks2,
                "ks3"=> $content->ks3,
                "ks4"=> $content->ks4,
                "ks5"=> $content->ks5,
                "ks6"=> $content->ks6,
                "ks7"=> $content->ks7,
                "ks8"=> $content->ks8,
                "ks9"=> $content->ks9,
                "ks10"=> $content->ks10,
                "ks11"=> $content->ks11,
                "ks12"=> $content->ks12,
                "ks13"=> $content->ks13,
                "ks14"=> $content->ks14,
                "ks15"=> $content->ks15,
                "ks16"=> $content->ks16,
                "ks17"=> $content->ks17,
                "ks18"=> $content->ks18,
                "ks19"=> $content->ks19,
                "ks20"=> $content->ks20,
                "ks21"=> $content->ks21,
                "ks22"=> $content->ks22,
                "ks23"=> $content->ks23,
                "ks24"=> $content->ks24,
                "ks25"=> $content->ks25,
                "ks26"=> $content->ks26,
                "ks27"=> $content->ks27,
                "ks28"=> $content->ks28,
                "ks29"=> $content->ks29,
                "ks30"=> $content->ks30,
                "ks31"=> $content->ks31,
                "ks32"=> $content->ks32,
                "ks33"=> $content->ks33,
                "ks34"=> $content->ks34,
                "ks35"=> $content->ks35,
                "ks36"=> $content->ks36,
                "ks37"=> $content->ks37,
                "ks38"=> $content->ks38,
                "ks39"=> $content->ks39,
                "ks40"=> $content->ks40,
                "ks41"=> $content->ks41,
                "ks42"=> $content->ks42,
                "ks43"=> $content->ks43,
                "ks44"=> $content->ks44,
                "ks45"=> $content->ks45,
                "ks46"=> $content->ks46,
                "ks47"=> $content->ks47,
                "ks48"=> $content->ks48,
                "ks49"=> $content->ks49,
                "ks50"=> $content->ks50,
                "ks51"=> $content->ks51,
                "ks52"=> $content->ks52,
                "ks53"=> $content->ks53,
                "ks54"=> $content->ks54,
                "ks55"=> $content->ks55,
                "ks56"=> $content->ks56,
                "ks57"=> $content->ks57,
                "ks58"=> $content->ks58,
                "ks59"=> $content->ks59,
                "ks60"=> $content->ks60,
                "ks61"=> $content->ks61,
                "ks62"=> $content->ks62,
                "ks63"=> $content->ks63,
                "ks64"=> $content->ks64,
                "ks65"=> $content->ks65,
                "ks66"=> $content->ks66,
                "ks67"=> $content->ks67,
                "ks68"=> $content->ks68,
                "ks69a"=> $content->ks69a,
                "ks69b"=> $content->ks69b,
                "ks69c"=> $content->ks69c,
                "ks69d"=> $content->ks69d,
                "ks69e"=> $content->ks69e,
                "ks69f"=> $content->ks69f,
                "ks69g"=> $content->ks69g,
                "ks69h"=> $content->ks69h,
                "ks69i"=> $content->ks69i,
                "ks69j"=> $content->ks69j,
                "ks69k"=> $content->ks69k,
                "ks69l"=> $content->ks69l,
                "ks70"=> $content->ks70,
                "sl1"=> $content->sl1,
                "sl1a"=> $content->sl1a,
                "sl2"=> $content->sl2,
                "sl2a"=> $content->sl2a,
                "sl3"=> $content->sl3,
                "sl3a"=> $content->sl3a,
                "sl4"=> $content->sl4,
                "sl4a"=> $content->sl4a,
                "sl5"=> $content->sl5,
                "sl5a"=> $content->sl5a,
                "sl6"=> $content->sl6,
                "sl6a"=> $content->sl6a,
                "sl7"=> $content->sl7,
                "sl7a"=> $content->sl7a,
                "sl8"=> $content->sl8,
                "sl8a"=> $content->sl8a,
                "sl9"=> $content->sl9,
                "sl9a"=> $content->sl9a,
                "sl10"=> $content->sl10,
                "sl10a"=> $content->sl10a,
                "sl11"=> $content->sl11,
                "sl12"=> $content->sl12,
                "sl13"=> $content->sl13,
                "sl14"=> $content->sl14,
                "sl15"=> $content->sl15,
                "sl16"=> $content->sl16,
                "sl17"=> $content->sl17,
                "sl18"=> $content->sl18,
                "sl19"=> $content->sl19,
                "sl20"=> $content->sl20,
                "sl21"=> $content->sl21,
                "sl22"=> $content->sl22,
                "sl23"=> $content->sl23,
                "sl24"=> $content->sl24,
                "sl24a"=> $content->sl24a,
                "sl25"=> $content->sl25,
                "sl26"=> $content->sl26,
                "sl27"=> $content->sl27,
                "createdBy" => $content->user_id,
                "last_updated_by" => $content->user_id,
            ]);
        }
    }
}
