<?php

use Illuminate\Database\Seeder;

class TerapiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contents = json_decode(file_get_contents(storage_path('database/terapi.json')));
        foreach($contents as $content) {
            DB::table('terapi')->insert([
                "id"=> $content->id_pemeriksaan_terapi,
                "id_pasien"=> $content->id_pasien,
                "kunjungan"=> intval($content->kunjungan),
                "tglPeriksa"=> $content->tgl_periksa,
                "medrec"=> $content->medrec,
                "b1"=> $content->b1,
                "b1a"=> $content->b1a,
                "b2"=> $content->b2,
                "b3"=> $content->b3,
                "b4"=> $content->b4,
                "b5"=> $content->b5,
                "b6"=> $content->b6,
                "b7"=> $content->b7,
                "b8"=> $content->b8,
                "b9"=> $content->b9, 
                "b10"=> $content->b10, 
                "b11"=> $content->b11, 
                "b12"=> $content->b12, 
                "b13"=> $content->b13, 
                "b14"=> $content->b14, 
                "b15"=> $content->b15, 
                "b16"=> $content->b16, 
                "b17"=> $content->b17,
                "b18"=> $content->b18,
                "b19"=> $content->b19, 
                "b20"=> $content->b20, 
                "b21"=> $content->b21, 
                "b22a"=> $content->b22a, 
                "b22b"=> $content->b22b, 
                "b22c"=> $content->b22c, 
                "b22d"=> $content->b22d, 
                "b22e"=> $content->b22e, 
                "b22f"=> $content->b22f,
                "b22g"=> $content->b22g,
                "b22h"=> $content->b22h, 
                "b22i"=> $content->b22i, 
                "b22j"=> $content->b22j, 
                "b22k"=> $content->b22k, 
                "b22l"=> $content->b22l, 
                "b22m"=> $content->b22m, 
                "b22n"=> $content->b22n, 
                "b22o"=> $content->b22o, 
                "b22p"=> $content->b22p,
                "b22q"=> $content->b22q,
                "b22r"=> $content->b22r, 
                "b22s"=> $content->b22s, 
                "b22t"=> $content->b22t, 
                "b22u"=> $content->b22u, 
                "b22v"=> $content->b22v, 
                "b22_lainnya"=> $content->b22_lainnya,
                "b23"=> $content->b23, 
                "b24"=> $content->b24, 
                "b25"=> $content->b25,
                "b26"=> $content->b26,
                "b27"=> $content->b27, 
                "b28"=> $content->b28, 
                "b29"=> $content->b29, 
                "b30"=> $content->b30, 
                "b31"=> $content->b31, 
                "b32"=> $content->b32, 
                "b33"=> $content->b33, 
                "b34"=> $content->b34, 
                "b35"=> $content->b35,
                "b36"=> $content->b36,
                "b37"=> $content->b37, 
                "b38"=> $content->b38, 
                "b39"=> $content->b39, 
                "b40"=> $content->b40, 
                "b41"=> $content->b41, 
                "b42"=> $content->b42, 
                "b43"=> $content->b43, 
                "b44"=> $content->b44, 
                "b45"=> $content->b45,
                "b46"=> $content->b46,
                "b47"=> $content->b47, 
                "b48"=> $content->b48, 
                "b49"=> $content->b49, 
                "b50"=> $content->b50, 
                "b51"=> $content->b51, 
                "sl1"=> $content->sl1, 
                "sl2"=> $content->sl2, 
                "sl3"=> $content->sl3, 
                "sl4"=> $content->sl4,
                "sl5"=> $content->sl5,
                "sl6"=> $content->sl6, 
                "sl7"=> $content->sl7, 
                "sl8"=> $content->sl8, 
                "sl9"=> $content->sl9, 
                "sl10"=> $content->sl10,                            
                "created_by" => $content->user_id,
                "last_updated_by" => $content->user_id,
            ]);
        }
    }
}
