@extends('layouts.layouts')

@section("styled")

@endsection

@section("content")
    <div class="header">
        <h2 class="header-title">Anamnesis</h2>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                <li class="breadcrumb-item "><a href="{{ route('anamnesis') }}">Anamnesis</a></li>
                <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-12 col-xl-12">
            @include("anamnesis.partials.form", [
                    'id' => '',
                    'nama_pasien' => '',
                    'id_pasien' => '',
                    'medrec' => '',
                    'kunjungan' => '',
                    'tanggal_periksa' => '',
                    'ka1' => '',
                    'ka2' => '',
                    'ka3' => '',
                    'ka4' => '',
                    'kb1' => '',
                    'kb2' => '',
                    'kb3' => '',
                    'kb4' => '',
                    'kc1' => '',
                    'kc2' => '',
                    'kd1' => '',
                    'kd2' => '',
                    'kd3' => '',
                    'ke1' => '',
                    'ke2' => '',
                    'kf1' => '',
                    'kg1' => '',
                    'kh1' => '',
                    'la' => '',
                    'ja1' => '',
                    'ja2' => '',
                    'ja2lainnya' => '',
                    'ja3' => '',
                    'ja3lainnya' => '',
                    'la1' => '',
                    'lb1' => '',
                    'lb1lainnya' => '',
                    'la3' => '',
                    'bc1' => '',
                    'bc2' => '',
                    'bc3' => '',
                    'bf1' => '',
                    'bf2' => '',
                    'bf3' => '',
                    'bb1' => '',
                    'bb2' => '',
                    'bb3' => '',
                    'bk1' => '',
                    'bk2' => '',
                    'bk3' => '',
                    'ba1' => '',
                    'ba2' => '',
                    'ba3' => '',
                    'bd1' => '',
                    'bd2' => '',
                    'bd3' => '',
                    'be1' => '',
                    'be2' => '',
                    'be3' => '',
                    'bj1' => '',
                    'bj2' => '',
                    'bj3' => '',
                    'bg1' => '',
                    'bg2' => '',
                    'bg3' => '',
                    'bh1' => '',
                    'bh2' => '',
                    'bh3' => '',
                    'bi1' => '',
                    'bi3' => '',
                    'ab1' => '',
                    'ab2' => '',
                    'ab3' => '',
                    'ac1' => '',
                    'ac2' => '',
                    'ac3' => '',
                    'ae1' => '',
                    'ae3' => '',
                    'ad1' => '',
                    'ad2' => '',
                    'ad3' => '',
                    'ai1' => '',
                    'ai2' => '',
                    'ai3' => '',
                    'aj1' => '',
                    'aj2' => '',
                    'aj3' => '',
                    'ag1' => '',
                    'ag2' => '',
                    'ag3' => '',
                    'ak1' => '',
                    'ak2' => '',
                    'ak3' => '',
                    'af1' => '',
                    'af2' => '',
                    'af3' => '',
                    'al1' => '',
                    'al3' => '',
                    'am1' => '',
                    'am21' => '',
                    'am22' => '',
                    'am23' => '',
                    'am24' => '',
                    'am25' => '',
                    'am26' => '',
                    'am27' => '',
                    'am28' => '',
                    'am29' => '',
                    'am210' => '',
                    'am211' => '',
                    'am212' => '',
                    'am3' => '',
                    'an1' => '',
                    'an3' => '',
                    'aa1' => '',
                    'aa2' => '',
                    'aa3' => '',
                    'ed1' => '',
                    'ed2' => '',
                    'ed3' => '',
                    'eb1' => '',
                    'eb2' => '',
                    'eb3' => '',
                    'eg1' => '',
                    'eg2' => '',
                    'eg3' => '',
                    'ef1' => '',
                    'ef3' => '',
                    'ea1' => '',
                    'ea2' => '',
                    'ea3' => '',
                    'ec1' => '',
                    'ec2' => '',
                    'ec3' => '',
                    'ee1' => '',
                    'ee3' => '',
                    'dc1' => '',
                    'dc2' => '',
                    'dc3' => '',
                    'dh1' => '',
                    'dh2' => '',
                    'da1' => '',
                    'da2' => '',
                    'da3' => '',
                    'de1' => '',
                    'de3' => '',
                    'dd1' => '',
                    'dd3' => '',
                    'df1' => '',
                    'df3' => '',
                    'di1' => '',
                    'di2' => '',
                    'dj1' => '',
                    'dj2' => '',
                    'dj3' => '',
                    'ca1' => '',
                    'ca2' => '',
                    'ca3' => '',
                    'cf1' => '',
                    'cf2' => '',
                    'cf3' => '',
                    'cd1' => '',
                    'cd2' => '',
                    'cd3' => '',
                    'cb1' => '',
                    'cb2' => '',
                    'cb3' => '',
                    'cg1' => '',
                    'cg2' => '',
                    'cg3' => '',
                    'cc1' => '',
                    'cc3' => '',
                    'ce1' => '',
                    'ce3' => '',
                    'ch1' => '',
                    'ch3' => '',
                    'ci1' => '',
                    'ci2' => '',
                    'ci3' => '',
                    'action' => ''
                ])
        </div>
    </div>

@endsection
@section('scripts')
    <script type="text/javascript">
    </script>
@endsection