@extends('layouts.layouts')

@section("styled")

@endsection

@section("content")
    <div class="header">
        <h2 class="header-title">Anamnesis</h2>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                <li class="breadcrumb-item "><a href="{{ route('anamnesis') }}">Anamnesis</a></li>
                <li class="breadcrumb-item active" aria-current="page">Create</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-12 col-xl-12">
            @include("anamnesis.partials.form", [
                    'id' => ''.'getId()',
                    'nama_pasien' => ''.'getPasien()->getNama()',
                    'id_pasien' => ''.'getPasien()->getId()',
                    'medrec' => ''.'getPasien()->getMedrec()',
                    'kunjungan' => ''.'getKunjungan()',
                    'tanggal_periksa' => ''.'getTanggalPeriksa()',
                    'ka1' => ''.'getKa1()',
                    'ka2' => ''.'getKa2()',
                    'ka3' => ''.'getKa3()',
                    'ka4' => ''.'getKa4()',
                    'kb1' => ''.'getKb1()',
                    'kb2' => ''.'getKb2()',
                    'kb3' => ''.'getKb3()',
                    'kb4' => ''.'getKb4()',
                    'kc1' => ''.'getKc1()',
                    'kc2' => ''.'getKc2()',
                    'kd1' => ''.'getKd1()',
                    'kd2' => ''.'getKd2()',
                    'kd3' => ''.'getKd3()',
                    'ke1' => ''.'getKe1()',
                    'ke2' => ''.'getKe2()',
                    'kf1' => ''.'getKf1()',
                    'kg1' => ''.'getKg1()',
                    'kh1' => ''.'getKh1()',
                    'la' => ''.'getLa()',
                    'ja1' => ''.'getJa1()',
                    'ja2' => ''.'getKa2()',
                    'ja2lainnya' => ''.'getJa2Lainnya()',
                    'ja3' => ''.'getJa3()',
                    'ja3lainnya' => ''.'getJa3Lainnya()',
                    'la1' => ''.'getLa1()',
                    'lb1' => ''.'getLb1()',
                    'lb1lainnya' => ''.'getLb1Lainnya()',
                    'la3' => ''.'getLa3()',
                    'bc1' => ''.'getBc1()',
                    'bc2' => ''.'getBc2()',
                    'bc3' => ''.'getBc3()',
                    'bf1' => ''.'getBf1()',
                    'bf2' => ''.'getBf2()',
                    'bf3' => ''.'getBf3()',
                    'bb1' => ''.'getBb1()',
                    'bb2' => ''.'getBb2()',
                    'bb3' => ''.'getBb3()',
                    'bk1' => ''.'getBk1()',
                    'bk2' => ''.'getBk2()',
                    'bk3' => ''.'getBk3()',
                    'ba1' => ''.'getBa1()',
                    'ba2' => ''.'getBa2()',
                    'ba3' => ''.'getBa3()',
                    'bd1' => ''.'getBd1()',
                    'bd2' => ''.'getBd2()',
                    'bd3' => ''.'getBd3()',
                    'be1' => ''.'getBe1()',
                    'be2' => ''.'getBe2()',
                    'be3' => ''.'getBe3()',
                    'bj1' => ''.'getBj1()',
                    'bj2' => ''.'getBj2()',
                    'bj3' => ''.'getBj3()',
                    'bg1' => ''.'getBg1()',
                    'bg2' => ''.'getBg2()',
                    'bg3' => ''.'getBg3()',
                    'bh1' => ''.'getBh1()',
                    'bh2' => ''.'getBh2()',
                    'bh3' => ''.'getBh3()',
                    'bi1' => ''.'getBi1()',
                    'bi3' => ''.'getBi3()',
                    'ab1' => ''.'getAb1()',
                    'ab2' => ''.'getAb2()',
                    'ab3' => ''.'getAb3()',
                    'ac1' => ''.'getAc1()',
                    'ac2' => ''.'getAc2()',
                    'ac3' => ''.'getAc3()',
                    'ae1' => ''.'getAe1()',
                    'ae3' => ''.'getAe3()',
                    'ad1' => ''.'getAd1()',
                    'ad2' => ''.'getAd2()',
                    'ad3' => ''.'getAd3()',
                    'ai1' => ''.'getAi1()',
                    'ai2' => ''.'getAi2()',
                    'ai3' => ''.'getAi3()',
                    'aj1' => ''.'getAj1()',
                    'aj2' => ''.'getAj2()',
                    'aj3' => ''.'getAj3()',
                    'ag1' => ''.'getAg1()',
                    'ag2' => ''.'getAg2()',
                    'ag3' => ''.'getAg3()',
                    'ak1' => ''.'getAk1()',
                    'ak2' => ''.'getAk2()',
                    'ak3' => ''.'getAk3()',
                    'af1' => ''.'getAf1()',
                    'af2' => ''.'getAf2()',
                    'af3' => ''.'getAf3()',
                    'al1' => ''.'getAl1()',
                    'al3' => ''.'getAl3()',
                    'am1' => ''.'getAm1()',
                    'am21' => ''.'getAm21()',
                    'am22' => ''.'getAm22()',
                    'am23' => ''.'getAm23()',
                    'am24' => ''.'getAm24()',
                    'am25' => ''.'getAm25()',
                    'am26' => ''.'getAm26()',
                    'am27' => ''.'getAm27()',
                    'am28' => ''.'getAm28()',
                    'am29' => ''.'getAm29()',
                    'am210' => ''.'getAm210()',
                    'am211' => ''.'getAm211()',
                    'am212' => ''.'getAm212()',
                    'am3' => ''.'getAm3()',
                    'an1' => ''.'getAn1()',
                    'an3' => ''.'getAn3()',
                    'aa1' => ''.'getAa1()',
                    'aa2' => ''.'getAa2()',
                    'aa3' => ''.'getAa3()',
                    'ed1' => ''.'getEd1()',
                    'ed2' => ''.'getEd2()',
                    'ed3' => ''.'getEd3()',
                    'eb1' => ''.'getEb1()',
                    'eb2' => ''.'getEb2()',
                    'eb3' => ''.'getEb3()',
                    'eg1' => ''.'getEg1()',
                    'eg2' => ''.'getEg2()',
                    'eg3' => ''.'getEg3()',
                    'ef1' => ''.'getEf1()',
                    'ef3' => ''.'getEf3()',
                    'ea1' => ''.'getEa1()',
                    'ea2' => ''.'getEa2()',
                    'ea3' => ''.'getEa3()',
                    'ec1' => ''.'getEc1()',
                    'ec2' => ''.'getEc2()',
                    'ec3' => ''.'getEc3()',
                    'ee1' => ''.'getEe1()',
                    'ee3' => ''.'getEe3()',
                    'dc1' => ''.'getDc1()',
                    'dc2' => ''.'getDc2()',
                    'dc3' => ''.'getDc3()',
                    'dh1' => ''.'getDh1()',
                    'dh2' => ''.'getDh2()',
                    'da1' => ''.'getDa1()',
                    'da2' => ''.'getDa2()',
                    'da3' => ''.'getDa3()',
                    'de1' => ''.'getDe1()',
                    'de3' => ''.'getDe3()',
                    'dd1' => ''.'getDd1()',
                    'dd3' => ''.'getDd3()',
                    'df1' => ''.'getDf1()',
                    'df3' => ''.'getDf3()',
                    'di1' => ''.'getDi1()',
                    'di2' => ''.'getDi2()',
                    'dj1' => ''.'getDj1()',
                    'dj2' => ''.'getDj2()',
                    'dj3' => ''.'getDj3()',
                    'ca1' => ''.'getCa1()',
                    'ca2' => ''.'getCa2()',
                    'ca3' => ''.'getCa3()',
                    'cf1' => ''.'getCf1()',
                    'cf2' => ''.'getCf2()',
                    'cf3' => ''.'getCf3()',
                    'cd1' => ''.'getCd1()',
                    'cd2' => ''.'getCd2()',
                    'cd3' => ''.'getCd3()',
                    'cb1' => ''.'getCb1()',
                    'cb2' => ''.'getCb2()',
                    'cb3' => ''.'getCb3()',
                    'cg1' => ''.'getCg1()',
                    'cg2' => ''.'getCg2()',
                    'cg3' => ''.'getCg3()',
                    'cc1' => ''.'getCc1()',
                    'cc3' => ''.'getCc3()',
                    'ce1' => ''.'getCe1()',
                    'ce3' => ''.'getCe3()',
                    'ch1' => ''.'getCh1()',
                    'ch3' => ''.'getCh3()',
                    'ci1' => ''.'getCi1()',
                    'ci2' => ''.'getCi2()',
                    'ci3' => ''.'getCi3()',
                    'action' => ''
                ])
        </div>
    </div>

@endsection
@section('scripts')
    <script type="text/javascript">
    </script>
@endsection