INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (0, '002', '2. RSCM Jakarta', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (327, '028', 'Dr Ramelan Surabaya', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (3617678, '033', 'RS Awal Bros Panam Pekanbaru', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (64476221, '025', 'RS Bhayangkara', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (2147483647, '030', 'RS Immanuel Bandung', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (5, '007', 'RS Moh. Hoesin Palembang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (709, '017', 'RS Muhammadiyah Palembang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (97, '005', 'RS Persahabatan Jakarta', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (40000000, '006', 'RS Ryacudu Lampung Utara', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (638, '026', 'RS Sanglah Bali', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (4, '014', 'RSAD TK II PELAMONIA Makassar', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (425, '003', 'RSDK (Kariadi) Semarang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (27, '004', 'RSHAM Medan', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (100, '001', 'RSHS Bandung', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (158, '011', 'RSKD Jakarta', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (779172, '029', 'RSU Haji Surabaya', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (619018, '016', 'RSU prop. NTB', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (1, '009', 'RSUD Abdul Wahab Syahranie Samarinda', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (399, '031', 'RSUD ARIFIN AHMAD Pekanbaru Riau', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (51, '015', 'RSUD dr MARGONO Purwokerto', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (27051850, '013', 'RSUD dr Moewardi Solo', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (8, '023', 'RSUD Dr Soedono Madiun', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (31882558, '032', 'RSUD Dr. Saiful Anwar Malang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (48202308, '020', 'RSUD Dr. Soetomo Surabaya', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (7, '022', 'Rsud indrasari rengat riau.', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (21, '024', 'RSUD Lawang Kab. Malang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (44, '027', 'RSUD Tenriawaru Bone SulSel', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (13927, '021', 'RSUD Ulin Banjarmasin', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (6, '008', 'RSUD Waled Cirebon', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (283, '012', 'RSUP Dr. M. Djamil Padang', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (578, '019', 'RSUP dr. Sardjito Jogja', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (22, '018', 'RSUZA Aceh', '', now(), 'admin', now(), 'admin');
INSERT INTO rumah_sakit (id, kode, nama, alamat, created_at, created_by, updated_at, last_updated_by) values (803, '010', 'RSWS Makassar', '', now(), 'admin', now(), 'admin');